export interface Astrologer {
  id: string;
  name: string;
  avatar: string;
  skills: string[];
  languages: string[];
  exp: number;
  price: number;
  rating: number;
  orders: number;
  isOnline: boolean;
  verified: boolean;
  followers: number;
  avgReply: string;
  videoPrice: number;
  consultingNow: number;
  chatSlots: number;
  videoSlots: number;
  bio: string;
  specialties: string[];
}

export const allAstrologers: Astrologer[] = [
  {
    id: '1',
    name: 'Shiva',
    avatar: 'https://media.chingari.io/apipublic/uploads/profilePic/26db47d6-13aa-40ee-b5a1-9299924cae9d.jpg',
    skills: ['Vedic', 'Numerology', 'Palmistry'],
    languages: ['Hindi', 'English', 'Bhojpuri'],
    exp: 6,
    price: 14,
    videoPrice: 18,
    rating: 4.0,
    orders: 120,
    isOnline: true,
    verified: true,
    followers: 24,
    avgReply: '45s',
    consultingNow: 87,
    chatSlots: 4,
    videoSlots: 5,
    bio: 'With 6 years of expertise in Vedic Astrology, Numerology, and Palmistry, Shiva has helped hundreds of individuals navigate life\'s most challenging moments. His deep-rooted knowledge of ancient Vedic texts combined with modern interpretations ensures each session is both enlightening and practical. Specializing in Career Guidance, Marriage Compatibility, Financial Planning, and Personal Growth, Shiva brings clarity to confusion with a warm, grounded approach.',
    specialties: ['Career Guidance', 'Marriage Compatibility', 'Financial Planning', 'Personal Growth', 'Vedic Predictions'],
  },
  {
    id: '2',
    name: 'Srahvya',
    avatar: 'https://media.chingari.io/apipublic/uploads/profilePic/0509b3e0-9221-467f-a007-3fb26bb36dcd.png',
    skills: ['Tarot', 'Numerology'],
    languages: ['English', 'Hindi'],
    exp: 8,
    price: 14,
    videoPrice: 18,
    rating: 5.0,
    orders: 310,
    isOnline: true,
    verified: true,
    followers: 52,
    avgReply: '30s',
    consultingNow: 134,
    chatSlots: 3,
    videoSlots: 6,
    bio: 'Srahvya is a gifted Tarot reader and Numerologist with 8 years of dedicated practice. Her intuitive readings and number-based insights have guided clients across India and beyond to make confident decisions in love, career, and life. She blends emotional intelligence with precise card interpretation to deliver profound, compassionate guidance that resonates long after the session ends.',
    specialties: ['Love & Relationships', 'Career Path', 'Tarot Readings', 'Numerology Reports', 'Life Path Analysis'],
  },
  {
    id: '3',
    name: 'Lavi',
    avatar: 'https://media.chingari.io/apipublic/uploads/profilePic/22dfc5d4-d377-46e1-81b0-c429b53b5025.png',
    skills: ['Vedic', 'Tarot', 'Face Reading'],
    languages: ['Hindi'],
    exp: 5,
    price: 16,
    videoPrice: 20,
    rating: 4.0,
    orders: 95,
    isOnline: true,
    verified: true,
    followers: 18,
    avgReply: '1m',
    consultingNow: 62,
    chatSlots: 5,
    videoSlots: 4,
    bio: 'Lavi combines the ancient art of Vedic Astrology with intuitive Tarot and the rare skill of Face Reading to offer a truly unique consultation experience. With 5 years of practice, she has honed the ability to read personality, potential, and purpose through multiple lenses. Her holistic approach ensures that every client leaves with actionable guidance and a deeper understanding of their cosmic blueprint.',
    specialties: ['Face Reading', 'Vedic Birth Chart', 'Tarot Guidance', 'Personality Analysis', 'Family Matters'],
  },
  {
    id: '4',
    name: 'Sonia',
    avatar: 'https://media.chingari.io/apipublic/uploads/profilePic/d0fc6f35-dcab-4eb0-bff6-114aa9cc8795.jpg',
    skills: ['Tarot', 'Psychic'],
    languages: ['Hindi'],
    exp: 4,
    price: 12,
    videoPrice: 15,
    rating: 5.0,
    orders: 210,
    isOnline: true,
    verified: true,
    followers: 39,
    avgReply: '25s',
    consultingNow: 99,
    chatSlots: 2,
    videoSlots: 3,
    bio: 'Sonia is a highly rated Tarot reader and Psychic intuitive who taps into deeper energies to provide guidance that goes beyond the physical. In just 4 years, she has built a loyal clientele who return for her uncanny accuracy and heartfelt advice. Whether you are facing uncertainty in love, career, or life direction, Sonia\'s sessions offer not just answers but genuine peace of mind.',
    specialties: ['Psychic Readings', 'Love & Romance', 'Energy Healing', 'Tarot Cards', 'Future Predictions'],
  },
  {
    id: '5',
    name: 'Mystery',
    avatar: 'https://media.chingari.io/apipublic/uploads/profilePic/fa0607c3-882c-42dd-93af-e28b7467c909.png',
    skills: ['Tarot', 'KP System'],
    languages: ['English', 'Hindi', 'Bengali'],
    exp: 5,
    price: 12,
    videoPrice: 12,
    rating: 3.55,
    orders: 11,
    isOnline: true,
    verified: true,
    followers: 10,
    avgReply: '30s',
    consultingNow: 119,
    chatSlots: 2,
    videoSlots: 7,
    bio: 'With 5 years of experience in Tarot Reading, Mystery Tarot has guided individuals toward clarity, healing, and self-discovery through intuitive and insightful readings. With a compassionate approach and deep spiritual understanding, every session is designed to provide honest guidance and practical direction. Specializing in Love & Relationships, Marriage, Career, Finance, Family Matters, and Personal Growth, Mystery Tarot combines the wisdom of the cards with a genuine desire to help you live your best life.',
    specialties: ['Love & Relationships', 'Marriage', 'Career', 'Finance', 'Family Matters', 'Personal Growth'],
  },
  {
    id: '6',
    name: 'Divyanshi',
    avatar: 'https://media.chingari.io/apipublic/uploads/profilePic/40d6d749-9c79-4454-b350-b76288fe6fcd.png',
    skills: ['Tarot', 'Vastu'],
    languages: ['Hindi', 'Bhojpuri'],
    exp: 5,
    price: 12,
    videoPrice: 15,
    rating: 5.0,
    orders: 180,
    isOnline: true,
    verified: true,
    followers: 31,
    avgReply: '40s',
    consultingNow: 75,
    chatSlots: 6,
    videoSlots: 8,
    bio: 'Divyanshi is an accomplished Tarot reader and Vastu expert with 5 years of guiding clients to create harmony in both their inner and outer worlds. Her Tarot sessions are grounded in spiritual wisdom while her Vastu consultations help transform living and working spaces into environments that support success, health, and positive energy. She brings warmth, clarity, and a deeply personal touch to every reading.',
    specialties: ['Vastu Shastra', 'Home & Office Energy', 'Tarot Guidance', 'Love & Marriage', 'Business Success'],
  },
  {
    id: '7',
    name: 'Dr. Radhika',
    avatar: 'https://media.chingari.io/apipublic/uploads/profilePic/0509b3e0-9221-467f-a007-3fb26bb36dcd.png',
    skills: ['Vedic', 'Nadi Astrology'],
    languages: ['English', 'Hindi', 'Marathi'],
    exp: 11,
    price: 25,
    videoPrice: 30,
    rating: 5.0,
    orders: 540,
    isOnline: true,
    verified: true,
    followers: 128,
    avgReply: '20s',
    consultingNow: 201,
    chatSlots: 3,
    videoSlots: 4,
    bio: 'Dr. Radhika holds a doctorate in Sanskrit and Ancient Vedic Studies, bringing unparalleled depth to her Vedic and Nadi Astrology consultations. With 11 years of practice, she has become one of the most sought-after astrologers on the platform, renowned for her precision and scholarly approach. Her consultations draw on ancient palm leaf manuscripts and classical texts, offering insights that are both timeless and transformative.',
    specialties: ['Nadi Astrology', 'Vedic Birth Chart', 'Dosha Analysis', 'Remedies & Rituals', 'Health & Longevity'],
  },
  {
    id: '8',
    name: 'Aacharya Anand',
    avatar: 'https://media.chingari.io/apipublic/uploads/profilePic/26db47d6-13aa-40ee-b5a1-9299924cae9d.jpg',
    skills: ['Vedic', 'Lal Kitab', 'Panchang'],
    languages: ['Hindi', 'Sanskrit'],
    exp: 15,
    price: 30,
    videoPrice: 35,
    rating: 5.0,
    orders: 890,
    isOnline: true,
    verified: true,
    followers: 312,
    avgReply: '15s',
    consultingNow: 248,
    chatSlots: 1,
    videoSlots: 2,
    bio: 'Aacharya Anand is a legendary figure in the world of Indian astrology with 15 years of dedicated practice spanning Vedic, Lal Kitab, and Panchang traditions. His guidance has touched thousands of lives across the country, offering remedies and predictions that have proven remarkably accurate. As a published author and spiritual teacher, his sessions combine scholarly depth with practical wisdom, making every consultation a truly life-changing experience.',
    specialties: ['Lal Kitab Remedies', 'Vedic Predictions', 'Panchang Muhurat', 'Business & Finance', 'Spiritual Guidance'],
  },
  {
    id: '101',
    name: 'Lavi',
    avatar: 'https://media.chingari.io/apipublic/uploads/profilePic/22dfc5d4-d377-46e1-81b0-c429b53b5025.png',
    skills: ['Vedic', 'Tarot', 'Face Reading'],
    languages: ['Hindi'],
    exp: 5,
    price: 16,
    videoPrice: 20,
    rating: 4.8,
    orders: 190,
    isOnline: true,
    verified: true,
    followers: 18,
    avgReply: '1m',
    consultingNow: 62,
    chatSlots: 5,
    videoSlots: 4,
    bio: 'Lavi combines the ancient art of Vedic Astrology with intuitive Tarot and the rare skill of Face Reading to offer a truly unique consultation experience. With 5 years of practice, she has honed the ability to read personality, potential, and purpose through multiple lenses. Her holistic approach ensures that every client leaves with actionable guidance and a deeper understanding of their cosmic blueprint.',
    specialties: ['Face Reading', 'Vedic Birth Chart', 'Tarot Guidance', 'Personality Analysis', 'Family Matters'],
  },
  {
    id: '102',
    name: 'Divyanshi',
    avatar: 'https://media.chingari.io/apipublic/uploads/profilePic/40d6d749-9c79-4454-b350-b76288fe6fcd.png',
    skills: ['Tarot', 'Vastu'],
    languages: ['Hindi', 'Bhojpuri'],
    exp: 5,
    price: 15,
    videoPrice: 18,
    rating: 4.9,
    orders: 230,
    isOnline: true,
    verified: true,
    followers: 31,
    avgReply: '40s',
    consultingNow: 75,
    chatSlots: 6,
    videoSlots: 8,
    bio: 'Divyanshi is an accomplished Tarot reader and Vastu expert with 5 years of guiding clients to create harmony in both their inner and outer worlds. Her Tarot sessions are grounded in spiritual wisdom while her Vastu consultations help transform living and working spaces into environments that support success, health, and positive energy. She brings warmth, clarity, and a deeply personal touch to every reading.',
    specialties: ['Vastu Shastra', 'Home & Office Energy', 'Tarot Guidance', 'Love & Marriage', 'Business Success'],
  },
  {
    id: '103',
    name: 'Shradha',
    avatar: 'https://media.chingari.io/apipublic/uploads/profilePic/0509b3e0-9221-467f-a007-3fb26bb36dcd.png',
    skills: ['Tarot', 'Numerology'],
    languages: ['English', 'Hindi', 'Kannada', 'Marathi'],
    exp: 9,
    price: 18,
    videoPrice: 22,
    rating: 4.9,
    orders: 410,
    isOnline: true,
    verified: true,
    followers: 76,
    avgReply: '35s',
    consultingNow: 158,
    chatSlots: 4,
    videoSlots: 5,
    bio: 'Shradha is a celebrated Tarot reader and Numerologist with 9 years of experience empowering individuals to decode the patterns of their lives. Her multilingual capabilities allow her to connect authentically with clients across diverse backgrounds. Known for her methodical approach and spiritual sensitivity, Shradha\'s sessions weave together card symbolism and numerical vibrations to reveal a comprehensive picture of your present circumstances and future potential.',
    specialties: ['Tarot Readings', 'Numerology', 'Love & Relationships', 'Career Guidance', 'Life Purpose'],
  },
  {
    id: '104',
    name: 'Guruji Shastri',
    avatar: 'https://media.chingari.io/apipublic/uploads/profilePic/26db47d6-13aa-40ee-b5a1-9299924cae9d.jpg',
    skills: ['Vedic', 'Panchang', 'Lal Kitab'],
    languages: ['Hindi', 'Gujarati'],
    exp: 14,
    price: 22,
    videoPrice: 28,
    rating: 5.0,
    orders: 680,
    isOnline: true,
    verified: true,
    followers: 215,
    avgReply: '20s',
    consultingNow: 320,
    chatSlots: 2,
    videoSlots: 3,
    bio: 'Guruji Shastri has spent 14 years mastering the sacred sciences of Vedic Astrology, Panchang computations, and Lal Kitab remedies. Revered by his vast following, he brings the wisdom of ancient traditions into practical, modern guidance. His Muhurat consultations are particularly sought-after for auspicious timings of weddings, business launches, and major life events. Every session with Guruji Shastri is an experience of profound clarity and spiritual alignment.',
    specialties: ['Muhurat Selection', 'Lal Kitab Remedies', 'Business Timing', 'Wedding Compatibility', 'Astrological Remedies'],
  },
];
